name: CI

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: env

      - name: Echo the current branch
        run: |
          echo "$GITHUB_REF_NAME"
